apiVersion: v1
kind: Service
metadata:
  name: randomquotes
  namespace: randomquotes
spec:
  selector:
    app: randomquotes
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
